// Soundbank of all available sounds.

export default new Array(
	{ name: "Campfire", file: "/nature/campfire.mp3" },
	{ name: "Droplets", file: "/nature/droplets.mp3" },
	{ name: "Wowling wind", file: "/nature/howling-wind.mp3" },
	{ name: "Jungle", file: "/nature/jungle.mp3" },
	{ name: "River", file: "/nature/river.mp3" },
	{ name: "Walk in snow", file: "/nature/walk-in-snow.mp3" },
	{ name: "Walk on leaves", file: "/nature/walk-on-leaves.mp3" },
	{ name: "Waterfall", file: "/nature/waterfall.mp3" },
	{ name: "Waves", file: "/nature/waves.mp3" },
	{ name: "Wind in trees", file: "/nature/wind-in-trees.mp3" },
	{ name: "Wind", file: "/nature/wind.mp3" },

	{ name: "Birds", file: "/animals/birds.mp3" },
	{ name: "Cat Purring", file: "/animals/cat-purring.mp3" },
	{ name: "Crickets", file: "/animals/crickets.mp3" },
	{ name: "Crows", file: "/animals/crows.mp3" },
	{ name: "Dog Barking", file: "/animals/dog-barking.mp3" },
	{ name: "Frog", file: "/animals/frog.mp3" },
	{ name: "Horse Gallop", file: "/animals/horse-galopp.mp3" },
	{ name: "Owl", file: "/animals/owl.mp3" },
	{ name: "Seagulls", file: "/animals/seagulls.mp3" },
	{ name: "Whale", file: "/animals/whale.mp3" },
	{ name: "Wolf", file: "/animals/wolf.mp3" },

	{ name: "Brown Noise", file: "/noise/brown-noise.wav" },
	{ name: "Pink Noise", file: "/noise/pink-noise.wav" },
	{ name: "White Noise", file: "/noise/white-noise.wav" },

	{ name: "Airport", file: "/places/airport.mp3" },
	{ name: "Cafe", file: "/places/cafe.mp3" },
	{ name: "Carousel", file: "/places/carousel.mp3" },
	{ name: "Church", file: "/places/church.mp3" },
	{ name: "Construction Site", file: "/places/construction-site.mp3" },
	{ name: "Crowded Bar", file: "/places/crowded-bar.mp3" },
	{ name: "Laboratory", file: "/places/laboratory.mp3" },
	{ name: "Laundry Room", file: "/places/laundry-room.mp3" },
	{ name: "Night Village", file: "/places/night-village.mp3" },
	{ name: "Office", file: "/places/office.mp3" },
	{ name: "Subway Station", file: "/places/subway-station.mp3" },
	{ name: "Supermarket", file: "/places/supermarket.mp3" },
	{ name: "Temple", file: "/places/temple.mp3" },
	{ name: "Underwater", file: "/places/underwater.mp3" },

	{ name: "Heavy Rain", file: "/rain/heavy-rain.mp3" },
	{ name: "Light Rain", file: "/rain/light-rain.mp3" },
	{ name: "Rain on Leaves", file: "/rain/rain-on-leaves.mp3" },
	{ name: "Rain on Tent", file: "/rain/rain-on-tent.mp3" },
	{ name: "Rain on Umbrella", file: "/rain/rain-on-umbrella.mp3" },
	{ name: "Rain on Window", file: "/rain/rain-on-window.mp3" },
	{ name: "Thunder", file: "/rain/thunder.mp3" },

	{ name: "Boiling Water", file: "/things/boiling-water.mp3" },
	{ name: "Bubbles", file: "/things/bubbles.mp3" },
	{ name: "Ceiling Fan", file: "/things/ceiling-fan.mp3" },
	{ name: "Clock", file: "/things/clock.mp3" },
	{ name: "Dryer", file: "/things/dryer.mp3" },
	{ name: "Keyboard", file: "/things/keyboard.mp3" },
	{ name: "Morse Code", file: "/things/morse-code.mp3" },
	{ name: "Paper", file: "/things/paper.mp3" },
	{ name: "Singing Bowl", file: "/things/singing-bowl.mp3" },
	{ name: "Slide Projector", file: "/things/slide-projector.mp3" },
	{ name: "Tuning Radio", file: "/things/tuning-radio.mp3" },
	{ name: "Typewriter", file: "/things/typewriter.mp3" },
	{ name: "Washing Machine", file: "/things/washing-machine.mp3" },
	{ name: "Wind Chimes", file: "/things/wind-chimes.mp3" },

	{ name: "Airplane", file: "/transport/airplane.mp3" },
	{ name: "Inside a Train", file: "/transport/inside-a-train.mp3" },
	{ name: "Rowing Boat", file: "/transport/rowing-boat.mp3" },
	{ name: "Sailboat", file: "/transport/sailboat.mp3" },
	{ name: "Submarine", file: "/transport/submarine.mp3" },
	{ name: "Train", file: "/transport/train.mp3" },

	{ name: "Ambulance Siren", file: "/urban/ambulance-siren.mp3" },
	{ name: "Busy Street", file: "/urban/busy-street.mp3" },
	{ name: "Crowd", file: "/urban/crowd.mp3" },
	{ name: "Fireworks", file: "/urban/fireworks.mp3" },
	{ name: "Highway", file: "/urban/highway.mp3" },
	{ name: "Road", file: "/urban/road.mp3" },
	{ name: "Traffic", file: "/urban/traffic.mp3" },
);
